# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69f3b3c930975c93bae8a8706810ff892a1245645780589eebe29aa0959f9fc1c037bb99753016eba60ccc7512c906428889783b7d93c5c9cd76ffc2dc862fb5

test:
  secret_key_base: 0bc62703a9d9be69b28621f25035880044e318880df23d4466bb039c26dd0e3c9b84f9caf9afbb1c8a4b001d2c46011277fe3b6142d9b315d5578527c8366479

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
